spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/teamflow_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


server.port=${PORT:8080}

# JWT Configuration
jwt.secret=${JWT_SECRET:YourVeryLongSecretKeyForJwtAuthenticationTeamFlow2026SecureKey}
jwt.expiration=86400000